x-common-env: &common_env
  DOMAIN: ${DOMAIN}
  MAIL_UID: ${MAIL_UID}
  MAIL_GID: ${MAIL_GID}
  MAIL_USER_NAME: ${MAIL_USER_NAME}

x-common-config: &common-config
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  init: true

services:
  postfix:
    build: 
      context: ./src/postfix
      dockerfile: Dockerfile
    image: my-postfix:latest
    container_name: postfix
    <<: *common-config
    # Allow binding to privileged ports that are less than 1024.
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "25:25"
      - "587:587"
    volumes:
    #   - ./src/postfix/config/main.cf:/etc/postfix/main.cf
    #   - ./data:/var/mail
    #   - ./src/letsencrypt/:/etc/letsencrypt/:ro
    #   - ./runtime/logs/postifix/:/var/log/
      - ./src/postfix/:/postfix/:ro
      - ./src/utility/:/utility/:ro
    #   - ./runtime/sockets/mail-services:/var/spool/postfix/private
    #   - ./data/vmaps:/etc/postfix/vmaps
    networks:
      - mailnet
    depends_on:
      - dkmi
    command: ["/bin/sh", "/postfix/start-postfix.sh"]
    environment:
      <<: *common_env

  dkmi:
    image: instrumentisto/opendkim:alpine
    container_name: dkmi
    ports:
      - "8891:8891"
    volumes:
      - ./src/dkmi/start-dkmi.sh:/start-dkmi.sh
      - ./src/dkmi/keys/:/etc/opendkim/keys/
    networks:
      - mailnet
    <<: *common-config
    entrypoint: ["/bin/sh", "/start-dkmi.sh"]
    environment:
      <<: *common_env

  # dovecot:
  #   build:
  #     context: ./src/dovecot
  #     dockerfile: Dockerfile
  #   image: my-dovecot:latest
  #   container_name: dovecot
  #   <<: *common-config
  #   ports:
  #     - "110:110"
  #     - "143:143"
  #     - "993:993"
  #     - "995:995"
  #   volumes:
  #     - ./data:/var/mail
  #     - ./src/dovecot/start-dovecot.sh:/start-dovecot.sh
  #     - ./src/dovecot/config/:/etc/dovecot/
  #     - ./src/letsencrypt/live/mail.wuchuheng.com/fullchain.pem:/etc/ssl/dovecot/fullchain.pem
  #     - ./src/letsencrypt/live/mail.wuchuheng.com/privkey.pem:/etc/ssl/dovecot/privkey.pem
  #     - ./runtime/sockets/mail-services:/var/spool/postfix/private
  #   restart: always
  #   networks:
  #     - mailnet
  #   command: ["/bin/sh", "/start-dovecot.sh"]
  #   init: true

networks:
  mailnet:
    driver: bridge