x-common-env: &common_env
  MAIL_DOMAIN: ${MAIL_DOMAIN}
  MAIL_UID: ${MAIL_UID}

x-common-config: &common-config
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  init: true

services:
  postfix:
    build: 
      context: ./src/postfix
      dockerfile: Dockerfile
    image: my-postfix:latest
    container_name: postfix
    <<: *common-config
    # Allow binding to privileged ports that are less than 1024.
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "25:25"
      - "587:587"
    volumes:
    #   - ./data:/var/mail
      - ./:/app/:ro
      - ./src/postfix/vmaps:/etc/postfix/vmaps
      - ./src/postfix/private/:/var/spool/postfix/private/
    networks:
      - mailnet
    depends_on:
      - dkmi
    command: ["/bin/sh", "/app/src/postfix/start-postfix.sh"]
    environment:
      <<: *common_env

  dkmi:
    image: instrumentisto/opendkim:alpine
    container_name: dkmi
    ports:
      - "8891:8891"
    volumes:
      - ./src/dkmi/keys/:/etc/opendkim/keys/
      - ./src/utility/:/utility/:ro
      - ./src/dkmi/:/dkmi/
    networks:
      - mailnet
    <<: *common-config
    entrypoint: ["/bin/sh", "/dkmi/start-dkmi.sh"]
    environment:
      <<: *common_env

  dovecot:
    build:
      context: ./src/dovecot
      dockerfile: Dockerfile
    image: my-dovecot:latest
    container_name: dovecot
    <<: *common-config
    environment:
      <<: *common_env
    depends_on:
      - postfix
    ports:
      - "143:143" # IMAP
      - "993:993" # IMAPS
    volumes:
      # - ./src/dovecot/start-dovecot.sh:/start-dovecot.sh
      # - ./src/letsencrypt/live/mail.wuchuheng.com/fullchain.pem:/etc/ssl/dovecot/fullchain.pem
      # - ./src/letsencrypt/live/mail.wuchuheng.com/privkey.pem:/etc/ssl/dovecot/privkey.pem
      - ./data:/var/mail
      - ./:/app/
      - ./src/postfix/private/:/var/spool/postfix/private/
      - ./src/dovecot/config/:/etc/dovecot/
    restart: always
    networks:
      - mailnet
    command: ["/bin/sh", "/app/src/dovecot/start-dovecot.sh"]

networks:
  mailnet:
    driver: bridge