# 定义通用的日志配置
x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  postfix:
    build: 
      context: ./src/postfix
      dockerfile: Dockerfile
    image: my-postfix:latest
    container_name: postfix
    hostname: mail.wuchuheng.com
    <<: *default-logging    # 使用通用日志配置
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./src/postfix/config/main.cf:/etc/postfix/main.cf
      - ./data:/var/mail
      - ./src/letsencrypt/:/etc/letsencrypt/:ro
      - ./runtime/logs/postifix/:/var/log/
      - ./src/postfix/start-postfix.sh:/start-postfix.sh
      - ./runtime/sockets/mail-services:/var/spool/postfix/private
    restart: always
    networks:
      - mailnet
    depends_on:
      - dkmi
    command: ["/bin/sh", "/start-postfix.sh"]
    user: root

  dkmi:
    image: instrumentisto/opendkim:alpine
    container_name: dkmi
    hostname: mail.wuchuheng.com
    ports:
      - "8891:8891"
    volumes:
      - ./src/dkmi/config/opendkmi.config:/etc/opendkim/opendkim.conf
      - ./src/dkmi/start-dkmi.sh:/start-dkmi.sh
      - ./src/dkmi/keys/:/etc/opendkim/keys/
    command: ["/bin/sh", "/start-dkmi.sh"]
    networks:
      - mailnet

  dovecot:
    build:
      context: ./src/dovecot
      dockerfile: Dockerfile
    image: my-dovecot:latest
    container_name: dovecot
    hostname: mail.wuchuheng.com
    <<: *default-logging    # 使用通用日志配置
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ./data:/var/mail
      - ./src/dovecot/start-dovecot.sh:/start-dovecot.sh
      - ./src/dovecot/config/:/etc/dovecot/
      - ./src/letsencrypt/live/mail.wuchuheng.com/fullchain.pem:/etc/ssl/dovecot/fullchain.pem
      - ./src/letsencrypt/live/mail.wuchuheng.com/privkey.pem:/etc/ssl/dovecot/privkey.pem
      - ./runtime/sockets/mail-services:/var/spool/postfix/private
    restart: always
    networks:
      - mailnet
    command: ["/bin/sh", "/start-dovecot.sh"]
    user: root

networks:
  mailnet:
    driver: bridge